/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as ScratchRouteImport } from './routes/scratch'
import { Route as RoboticaRouteImport } from './routes/robotica'
import { Route as PythonRouteImport } from './routes/python'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as ClubesDeEstudoRouteImport } from './routes/clubes-de-estudo'
import { Route as IndexRouteImport } from './routes/index'

const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchRoute = ScratchRouteImport.update({
  id: '/scratch',
  path: '/scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const RoboticaRoute = RoboticaRouteImport.update({
  id: '/robotica',
  path: '/robotica',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesDeEstudoRoute = ClubesDeEstudoRouteImport.update({
  id: '/clubes-de-estudo',
  path: '/clubes-de-estudo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clubes-de-estudo': typeof ClubesDeEstudoRoute
  '/escolas': typeof EscolasRoute
  '/python': typeof PythonRoute
  '/robotica': typeof RoboticaRoute
  '/scratch': typeof ScratchRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clubes-de-estudo': typeof ClubesDeEstudoRoute
  '/escolas': typeof EscolasRoute
  '/python': typeof PythonRoute
  '/robotica': typeof RoboticaRoute
  '/scratch': typeof ScratchRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clubes-de-estudo': typeof ClubesDeEstudoRoute
  '/escolas': typeof EscolasRoute
  '/python': typeof PythonRoute
  '/robotica': typeof RoboticaRoute
  '/scratch': typeof ScratchRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clubes-de-estudo'
    | '/escolas'
    | '/python'
    | '/robotica'
    | '/scratch'
    | '/sobre-nos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clubes-de-estudo'
    | '/escolas'
    | '/python'
    | '/robotica'
    | '/scratch'
    | '/sobre-nos'
  id:
    | '__root__'
    | '/'
    | '/clubes-de-estudo'
    | '/escolas'
    | '/python'
    | '/robotica'
    | '/scratch'
    | '/sobre-nos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubesDeEstudoRoute: typeof ClubesDeEstudoRoute
  EscolasRoute: typeof EscolasRoute
  PythonRoute: typeof PythonRoute
  RoboticaRoute: typeof RoboticaRoute
  ScratchRoute: typeof ScratchRoute
  SobreNosRoute: typeof SobreNosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratch': {
      id: '/scratch'
      path: '/scratch'
      fullPath: '/scratch'
      preLoaderRoute: typeof ScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robotica': {
      id: '/robotica'
      path: '/robotica'
      fullPath: '/robotica'
      preLoaderRoute: typeof RoboticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes-de-estudo': {
      id: '/clubes-de-estudo'
      path: '/clubes-de-estudo'
      fullPath: '/clubes-de-estudo'
      preLoaderRoute: typeof ClubesDeEstudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubesDeEstudoRoute: ClubesDeEstudoRoute,
  EscolasRoute: EscolasRoute,
  PythonRoute: PythonRoute,
  RoboticaRoute: RoboticaRoute,
  ScratchRoute: ScratchRoute,
  SobreNosRoute: SobreNosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
